# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timelapse_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1099, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton_ipnut_folder = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_ipnut_folder.setGeometry(QtCore.QRect(480, 170, 27, 22))
        self.toolButton_ipnut_folder.setObjectName("toolButton_ipnut_folder")
        self.label_input_folder = QtWidgets.QLabel(self.centralwidget)
        self.label_input_folder.setGeometry(QtCore.QRect(70, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_input_folder.setFont(font)
        self.label_input_folder.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_input_folder.setObjectName("label_input_folder")
        self.toolButton_output_folder = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_output_folder.setGeometry(QtCore.QRect(480, 220, 27, 22))
        self.toolButton_output_folder.setObjectName("toolButton_output_folder")
        self.label_output_folder = QtWidgets.QLabel(self.centralwidget)
        self.label_output_folder.setGeometry(QtCore.QRect(70, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_output_folder.setFont(font)
        self.label_output_folder.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_output_folder.setObjectName("label_output_folder")
        self.comboBox_video_format = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_video_format.setGeometry(QtCore.QRect(240, 270, 231, 22))
        self.comboBox_video_format.setObjectName("comboBox_video_format")
        self.label_video_format = QtWidgets.QLabel(self.centralwidget)
        self.label_video_format.setGeometry(QtCore.QRect(50, 260, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_video_format.setFont(font)
        self.label_video_format.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_video_format.setObjectName("label_video_format")
        self.label_fps = QtWidgets.QLabel(self.centralwidget)
        self.label_fps.setGeometry(QtCore.QRect(50, 310, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_fps.setFont(font)
        self.label_fps.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_fps.setObjectName("label_fps")
        self.fps_slider = QtWidgets.QSlider(self.centralwidget)
        self.fps_slider.setGeometry(QtCore.QRect(240, 320, 231, 22))
        self.fps_slider.setAutoFillBackground(False)
        self.fps_slider.setMinimum(1)
        self.fps_slider.setMaximum(120)
        self.fps_slider.setSliderPosition(25)
        self.fps_slider.setOrientation(QtCore.Qt.Horizontal)
        self.fps_slider.setObjectName("fps_slider")
        self.pushButton_convert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_convert.setEnabled(True)
        self.pushButton_convert.setGeometry(QtCore.QRect(240, 370, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_convert.setFont(font)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(210, 160, 20, 271))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(240, 440, 291, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.lineEdit_input_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input_folder.setGeometry(QtCore.QRect(240, 170, 231, 22))
        self.lineEdit_input_folder.setObjectName("lineEdit_input_folder")
        self.lineEdit_output_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_output_folder.setGeometry(QtCore.QRect(240, 220, 231, 22))
        self.lineEdit_output_folder.setObjectName("lineEdit_output_folder")
        self.label_app_name = QtWidgets.QLabel(self.centralwidget)
        self.label_app_name.setGeometry(QtCore.QRect(70, 40, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Imprint MT Shadow")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_app_name.setFont(font)
        self.label_app_name.setObjectName("label_app_name")
        self.label_fps_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_fps_2.setGeometry(QtCore.QRect(490, 320, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_fps_2.setFont(font)
        self.label_fps_2.setObjectName("label_fps_2")
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setEnabled(True)
        self.pushButton_quit.setGeometry(QtCore.QRect(890, 550, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setEnabled(True)
        self.pushButton_about.setGeometry(QtCore.QRect(730, 550, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_about.setFont(font)
        self.pushButton_about.setObjectName("pushButton_about")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 490, 471, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_image_preview = QtWidgets.QLabel(self.centralwidget)
        self.label_image_preview.setGeometry(QtCore.QRect(570, 160, 461, 291))
        self.label_image_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_preview.setObjectName("label_image_preview")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(570, 160, 461, 291))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1099, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_video_format.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JJ - Timelapse tool"))
        self.toolButton_ipnut_folder.setText(_translate("MainWindow", "..."))
        self.label_input_folder.setText(_translate("MainWindow", "Input folder:"))
        self.toolButton_output_folder.setText(_translate("MainWindow", "..."))
        self.label_output_folder.setText(_translate("MainWindow", "Output folder:"))
        self.label_video_format.setText(_translate("MainWindow", "Video format:"))
        self.label_fps.setText(_translate("MainWindow", "FPS:"))
        self.pushButton_convert.setText(_translate("MainWindow", "Convert"))
        self.label_app_name.setText(_translate("MainWindow", "JJ - Timelapse tool"))
        self.label_fps_2.setText(_translate("MainWindow", "25"))
        self.pushButton_quit.setText(_translate("MainWindow", "Quit"))
        self.pushButton_about.setText(_translate("MainWindow", "About"))
        self.label_image_preview.setText(_translate("MainWindow", "Preview"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
